def name = 'demo'
def buildNamespace = 'cicd'
def deployNamespaces = ['dev', 'test', 'pre-prod', 'prod']

def tags, tag, deployTo

stage('Selection') {
  openshift.withCluster(){
    is = openshift.selector('is', name).object()
    tags = is.status.tags.collect{it.tag}.join('\n')
  }
  
  timeout(time: 5, unit: 'MINUTES') {
    deploy = input(
      	id: 'Proceed', 
      	message: 'Specify Deployment', 
      	parameters: [
      		[$class: 'ChoiceParameterDefinition', choices: deployNamespaces.join('\n'), description: 'Deploy to', name: 'deployTo'],
      		[$class: 'ChoiceParameterDefinition', choices: tags, description: 'Deploy version?', name: 'tag']
      	]
    )
      
    deployTo = deploy['deployTo']
    tag = deploy['tag']
  }
}

stage("Deployment") {
  echo "Deploying ${buildNamespace}/${name}:${tag} to ${deployTo}" 
     
  openshift.withCluster() { 
    openshift.tag("${buildNamespace}/${name}:${tag}", "${deployTo}/${name}:latest") 
  } 
}
